[package]
name = "iupac"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
paste = "1.0.15"
petgraph = { version = "0.6.5", features = ["serde-1"] }
serde_json = "1.0.120"

[dependencies.bevy]
version = "0.13.2"
default-features = false
features = ["bevy_winit", "bevy_ui", "wayland", "dynamic_linking", "bevy_gizmos"]
