[package]
name = "iupac"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
paste = "1.0.15"
petgraph = { version = "0.6.5", features = ["serde-1"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
