[package]
name = "inchi"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph.workspace = true

red_book.workspace = true

[dev-dependencies]
paste.workspace = true

blue_book.workspace = true
