[package]
name = "blue_book"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static.workspace = true
petgraph.workspace = true
serde.workspace = true

parsing.workspace = true
red_book.workspace = true

[dev-dependencies]
paste.workspace = true
serde_json.workspace = true
